#!/bin/bash

set -eu

REPO_DIR="$( dirname -- "$( readlink -f -- "$0"; )"; )"

mkdir -p ~/.local/share/texmf/tex/latex/local

grep -v '^#' packages.txt | while read -r p; do
    rm -r ~/.local/share/texmf/tex/latex/local/"$p" || true
    echo "$REPO_DIR/$p -> ~/.local/share/texmf/tex/latex/local"
    cp -r "$REPO_DIR/$p" ~/.local/share/texmf/tex/latex/local/
done
