#!/bin/bash

set -eux

REPO_DIR="$( dirname -- "$( readlink -f -- "$0"; )"; )"

mkdir -p ~/.local/share/texmf/tex/latex/local

rm -r ~/.local/share/texmf/tex/latex/local/{hw,stats,xemacros,comp} || true

cp -r "$REPO_DIR"/{hw,stats,xemacros,comp} ~/.local/share/texmf/tex/latex/local/
